GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "Wayne Haworth",
    "likes": 0,
    "title": "Find out more about me",
    "url": "www.waynehaworth.com/moreinfo"
}